version: '3.8'

services:
  # PostgreSQL Database
  database:
    image: postgres:15
    container_name: car_accident_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: car_accident_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: car_accident_backend
    restart: always
    environment:
      - POSTGRES_SERVER=database
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=car_accident_db
      - SECRET_KEY=your-secret-key-here-change-in-production
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - database
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: car_accident_frontend
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  # ML Training Worker (optional)
  ml-worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: car_accident_ml_worker
    restart: always
    volumes:
      - ./backend:/app
    command: python ml/train.py --data sample_training_data.csv
    depends_on:
      - database

volumes:
  postgres_data: